spring:
  application:
    name: publicze_platform
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 14faa171-43ba-43b2-910f-54788531c0bb
      config:
        server-addr: 127.0.0.1:8848
        name: publicze_platform
        namespace: 14faa171-43ba-43b2-910f-54788531c0bb
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}