
name: Deploy to ACR and ECS
 
on:
  push:
    branches:
      - main  # 或者你想要自动部署的分支 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://crpi-5ib73szbrjh3wsd8.cn-hangzhou.personal.cr.aliyuncs.com  # 根据你的ACR区域修改登录服务器地址
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push Docker image
      run: |
        docker build -t crpi-5ib73szbrjh3wsd8.cn-hangzhou.personal.cr.aliyuncs.com/deep-space1/registry/publicze-platform:latest .
        docker push crpi-5ib73szbrjh3wsd8.cn-hangzhou.personal.cr.aliyuncs.com/deep-space1/registry/publicze-platform:latest
