name: Push to ACR
 
on: [push]
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to ACR
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.ACR_REGISTRY }}/publicze:latest
        
    - name: Set up K8s tools
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.20.7' # 设置你需要的 kubectl 版本
    
    - name: Decode kubeconfig and set KUBECONFIG environment variable
      run: |
        echo ${{ secrets.KUBECONFIG_BASE64 }} | base64 --decode > /tmp/kubeconfig.yaml
        export KUBECONFIG=/tmp/kubeconfig.yaml
        kubectl config view --raw > /tmp/kubeconfig.yaml  # 再次确认设置环境变量正确加载 kubeconfig 文件
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-deployment.yaml  # 使用你的部署文件路径替换 k8s-deployment.yaml
