


name: Deploy to ACR
 
on:
  push:
    branches:
      - main  # 触发分支，根据需要修改
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
 
    - name: Build with Maven
      run: mvn -B package --file publicze_platform/pom.xml
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://crpi-5ib73szbrjh3wsd8.cn-hangzhou.personal.cr.aliyuncs.com  # 你的ACR登录服务器地址，例如 registry.cn-hangzhou.aliyuncs.com
        username: '${{ secrets.ACR_USERNAME }}'  # GitHub的secrets变量
        password: '${{ secrets.ACR_PASSWORD }}'  # GitHub的secrets变量
    - name: Build Docker image 
      run: docker build . --file Dockerfile --tag publicze-platform:v1.0.0

    #- name: Tag Docker image # 标记 Docker 镜像
    #  run: docker tag publicze-platform:v1.0.0 https://registry.cn-hangzhou.aliyuncs.com/deep-space1/registry/publicze-platform:v1.0.0

    - name: Push Docker image # 推送 Docker 镜像到仓库
      run: docker push https://registry.cn-hangzhou.aliyuncs.com/deep-space1/registry/publicze-platform:v1.0.0
    #- name: Build and push Docker image for Backend
    #  uses: docker/build-push-action@v4
    #  with:
    #    context: ./publicze # 确保这是你后端 Dockerfile 所在的目录相对于仓库根目录
    #    file: ./publicze/Dockerfile # Dockerfile 的路径
    #    push: true
    #    tags: |
    #       https://registry.cn-hangzhou.aliyuncs.com/deep-space1/registry:latest
    #       https://registry.cn-hangzhou.aliyuncs.com/deep-space1/registry:latest
          # YOUR_ACR_NAMESPACE 替换为你的ACR命名空间
   # - name: Build and push Docker image
   #   run: |
   #     docker build -t publicze-platform:latest
   #     docker tag publicze-platform:latest https://registry.cn-hangzhou.aliyuncs.com/deep-space1/registry/publicze-platform:latest
   #     docker push https://registry.cn-hangzhou.aliyuncs.com/deep-space1/registry/publicze-platform:latest
